### ISSUE TITLE
AM should be possible below 76MHz and in range 108-136MHz only

### ISSUE THREAD

**Issue by pawol** [Tunas1337/UV-K5-Modded-Firmwares#11] opened 2023-06-02 20:58 UTC
AM should be possible below 76MHz and in range 108-136MHz only.
Other bands do not use AM at all.

**Comment by streamofstars** [comment] 2023-06-03 10:56
More or less duplicate of #10, see [my comment there](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/issues/10#issuecomment-1574854546) explaining other usage of AM in slightly higher frequencies than 136 MHz.

**Comment by Tunas1337** [comment] 2023-06-03 19:10
Seconded. Again, people have been using AM above 136MHz already.

**Closed by Tunas1337** 2023-06-03 19:10 UTC
